// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org.game.packer.proto

package com.sean.packer.proto;

public final class Packer {
  private Packer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.ziv.MsgType}
   */
  public enum MsgType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SYNCHOTPACK = 0;</code>
     */
    SYNCHOTPACK(0),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SYNCHOTPACK = 0;</code>
     */
    public static final int SYNCHOTPACK_VALUE = 0;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgType valueOf(int value) {
      return forNumber(value);
    }

    public static MsgType forNumber(int value) {
      switch (value) {
        case 0: return SYNCHOTPACK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MsgType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
            public MsgType findValueByNumber(int number) {
              return MsgType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Packer.getDescriptor().getEnumTypes().get(0);
    }

    private static final MsgType[] VALUES = values();

    public static MsgType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MsgType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.ziv.MsgType)
  }

  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ziv.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.ziv.MsgType msgType = 1;</code>
     */
    int getMsgTypeValue();
    /**
     * <code>.com.ziv.MsgType msgType = 1;</code>
     */
    Packer.MsgType getMsgType();

    /**
     * <code>.com.ziv.SyncHotPack syncHotPack = 2;</code>
     */
    boolean hasSyncHotPack();
    /**
     * <code>.com.ziv.SyncHotPack syncHotPack = 2;</code>
     */
    Packer.SyncHotPack getSyncHotPack();
    /**
     * <code>.com.ziv.SyncHotPack syncHotPack = 2;</code>
     */
    Packer.SyncHotPackOrBuilder getSyncHotPackOrBuilder();

    public Packer.Message.MsgCase getMsgCase();
  }
  /**
   * Protobuf type {@code com.ziv.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ziv.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      msgType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              msgType_ = rawValue;
              break;
            }
            case 18: {
              Packer.SyncHotPack.Builder subBuilder = null;
              if (msgCase_ == 2) {
                subBuilder = ((Packer.SyncHotPack) msg_).toBuilder();
              }
              msg_ =
                  input.readMessage(Packer.SyncHotPack.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((Packer.SyncHotPack) msg_);
                msg_ = subBuilder.buildPartial();
              }
              msgCase_ = 2;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_com_ziv_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_com_ziv_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Packer.Message.class, Packer.Message.Builder.class);
    }

    private int msgCase_ = 0;
    private java.lang.Object msg_;
    public enum MsgCase
        implements com.google.protobuf.Internal.EnumLite {
      SYNCHOTPACK(2),
      MSG_NOT_SET(0);
      private final int value;
      private MsgCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MsgCase valueOf(int value) {
        return forNumber(value);
      }

      public static MsgCase forNumber(int value) {
        switch (value) {
          case 2: return SYNCHOTPACK;
          case 0: return MSG_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MsgCase
    getMsgCase() {
      return MsgCase.forNumber(
          msgCase_);
    }

    public static final int MSGTYPE_FIELD_NUMBER = 1;
    private int msgType_;
    /**
     * <code>.com.ziv.MsgType msgType = 1;</code>
     */
    public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <code>.com.ziv.MsgType msgType = 1;</code>
     */
    public Packer.MsgType getMsgType() {
      @SuppressWarnings("deprecation")
      Packer.MsgType result = Packer.MsgType.valueOf(msgType_);
      return result == null ? Packer.MsgType.UNRECOGNIZED : result;
    }

    public static final int SYNCHOTPACK_FIELD_NUMBER = 2;
    /**
     * <code>.com.ziv.SyncHotPack syncHotPack = 2;</code>
     */
    public boolean hasSyncHotPack() {
      return msgCase_ == 2;
    }
    /**
     * <code>.com.ziv.SyncHotPack syncHotPack = 2;</code>
     */
    public Packer.SyncHotPack getSyncHotPack() {
      if (msgCase_ == 2) {
         return (Packer.SyncHotPack) msg_;
      }
      return Packer.SyncHotPack.getDefaultInstance();
    }
    /**
     * <code>.com.ziv.SyncHotPack syncHotPack = 2;</code>
     */
    public Packer.SyncHotPackOrBuilder getSyncHotPackOrBuilder() {
      if (msgCase_ == 2) {
         return (Packer.SyncHotPack) msg_;
      }
      return Packer.SyncHotPack.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgType_ != Packer.MsgType.SYNCHOTPACK.getNumber()) {
        output.writeEnum(1, msgType_);
      }
      if (msgCase_ == 2) {
        output.writeMessage(2, (Packer.SyncHotPack) msg_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgType_ != Packer.MsgType.SYNCHOTPACK.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgType_);
      }
      if (msgCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (Packer.SyncHotPack) msg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Packer.Message)) {
        return super.equals(obj);
      }
      Packer.Message other = (Packer.Message) obj;

      if (msgType_ != other.msgType_) return false;
      if (!getMsgCase().equals(other.getMsgCase())) return false;
      switch (msgCase_) {
        case 2:
          if (!getSyncHotPack()
              .equals(other.getSyncHotPack())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + msgType_;
      switch (msgCase_) {
        case 2:
          hash = (37 * hash) + SYNCHOTPACK_FIELD_NUMBER;
          hash = (53 * hash) + getSyncHotPack().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Packer.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Packer.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Packer.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Packer.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Packer.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Packer.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Packer.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Packer.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Packer.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Packer.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Packer.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Packer.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Packer.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ziv.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ziv.Message)
        Packer.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_com_ziv_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_com_ziv_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Packer.Message.class, Packer.Message.Builder.class);
      }

      // Construct using org.game.packer.proto.Packer.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        msgType_ = 0;

        msgCase_ = 0;
        msg_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_com_ziv_Message_descriptor;
      }

      @java.lang.Override
      public Packer.Message getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @java.lang.Override
      public Packer.Message build() {
        Packer.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Packer.Message buildPartial() {
        Packer.Message result = new Packer.Message(this);
        result.msgType_ = msgType_;
        if (msgCase_ == 2) {
          if (syncHotPackBuilder_ == null) {
            result.msg_ = msg_;
          } else {
            result.msg_ = syncHotPackBuilder_.build();
          }
        }
        result.msgCase_ = msgCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Packer.Message) {
          return mergeFrom((Packer.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Packer.Message other) {
        if (other == getDefaultInstance()) return this;
        if (other.msgType_ != 0) {
          setMsgTypeValue(other.getMsgTypeValue());
        }
        switch (other.getMsgCase()) {
          case SYNCHOTPACK: {
            mergeSyncHotPack(other.getSyncHotPack());
            break;
          }
          case MSG_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Packer.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Packer.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int msgCase_ = 0;
      private java.lang.Object msg_;
      public MsgCase
          getMsgCase() {
        return MsgCase.forNumber(
            msgCase_);
      }

      public Builder clearMsg() {
        msgCase_ = 0;
        msg_ = null;
        onChanged();
        return this;
      }


      private int msgType_ = 0;
      /**
       * <code>.com.ziv.MsgType msgType = 1;</code>
       */
      public int getMsgTypeValue() {
        return msgType_;
      }
      /**
       * <code>.com.ziv.MsgType msgType = 1;</code>
       */
      public Builder setMsgTypeValue(int value) {
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.ziv.MsgType msgType = 1;</code>
       */
      public Packer.MsgType getMsgType() {
        @SuppressWarnings("deprecation")
        Packer.MsgType result = Packer.MsgType.valueOf(msgType_);
        return result == null ? Packer.MsgType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.ziv.MsgType msgType = 1;</code>
       */
      public Builder setMsgType(Packer.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.ziv.MsgType msgType = 1;</code>
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          Packer.SyncHotPack, Packer.SyncHotPack.Builder, Packer.SyncHotPackOrBuilder> syncHotPackBuilder_;
      /**
       * <code>.com.ziv.SyncHotPack syncHotPack = 2;</code>
       */
      public boolean hasSyncHotPack() {
        return msgCase_ == 2;
      }
      /**
       * <code>.com.ziv.SyncHotPack syncHotPack = 2;</code>
       */
      public Packer.SyncHotPack getSyncHotPack() {
        if (syncHotPackBuilder_ == null) {
          if (msgCase_ == 2) {
            return (Packer.SyncHotPack) msg_;
          }
          return Packer.SyncHotPack.getDefaultInstance();
        } else {
          if (msgCase_ == 2) {
            return syncHotPackBuilder_.getMessage();
          }
          return Packer.SyncHotPack.getDefaultInstance();
        }
      }
      /**
       * <code>.com.ziv.SyncHotPack syncHotPack = 2;</code>
       */
      public Builder setSyncHotPack(Packer.SyncHotPack value) {
        if (syncHotPackBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          syncHotPackBuilder_.setMessage(value);
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.com.ziv.SyncHotPack syncHotPack = 2;</code>
       */
      public Builder setSyncHotPack(
          Packer.SyncHotPack.Builder builderForValue) {
        if (syncHotPackBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          syncHotPackBuilder_.setMessage(builderForValue.build());
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.com.ziv.SyncHotPack syncHotPack = 2;</code>
       */
      public Builder mergeSyncHotPack(Packer.SyncHotPack value) {
        if (syncHotPackBuilder_ == null) {
          if (msgCase_ == 2 &&
              msg_ != Packer.SyncHotPack.getDefaultInstance()) {
            msg_ = Packer.SyncHotPack.newBuilder((Packer.SyncHotPack) msg_)
                .mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          if (msgCase_ == 2) {
            syncHotPackBuilder_.mergeFrom(value);
          }
          syncHotPackBuilder_.setMessage(value);
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.com.ziv.SyncHotPack syncHotPack = 2;</code>
       */
      public Builder clearSyncHotPack() {
        if (syncHotPackBuilder_ == null) {
          if (msgCase_ == 2) {
            msgCase_ = 0;
            msg_ = null;
            onChanged();
          }
        } else {
          if (msgCase_ == 2) {
            msgCase_ = 0;
            msg_ = null;
          }
          syncHotPackBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.com.ziv.SyncHotPack syncHotPack = 2;</code>
       */
      public Packer.SyncHotPack.Builder getSyncHotPackBuilder() {
        return getSyncHotPackFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.ziv.SyncHotPack syncHotPack = 2;</code>
       */
      public Packer.SyncHotPackOrBuilder getSyncHotPackOrBuilder() {
        if ((msgCase_ == 2) && (syncHotPackBuilder_ != null)) {
          return syncHotPackBuilder_.getMessageOrBuilder();
        } else {
          if (msgCase_ == 2) {
            return (Packer.SyncHotPack) msg_;
          }
          return Packer.SyncHotPack.getDefaultInstance();
        }
      }
      /**
       * <code>.com.ziv.SyncHotPack syncHotPack = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Packer.SyncHotPack, Packer.SyncHotPack.Builder, Packer.SyncHotPackOrBuilder>
          getSyncHotPackFieldBuilder() {
        if (syncHotPackBuilder_ == null) {
          if (!(msgCase_ == 2)) {
            msg_ = Packer.SyncHotPack.getDefaultInstance();
          }
          syncHotPackBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Packer.SyncHotPack, Packer.SyncHotPack.Builder, Packer.SyncHotPackOrBuilder>(
                  (Packer.SyncHotPack) msg_,
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        msgCase_ = 2;
        onChanged();;
        return syncHotPackBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ziv.Message)
    }

    // @@protoc_insertion_point(class_scope:com.ziv.Message)
    private static final Packer.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Packer.Message();
    }

    public static Packer.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Packer.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SyncHotPackOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ziv.SyncHotPack)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *1:android 2:ios
     * </pre>
     *
     * <code>int32 platform = 1;</code>
     */
    int getPlatform();

    /**
     * <pre>
     *主版本号
     * </pre>
     *
     * <code>int32 majorVersion = 2;</code>
     */
    int getMajorVersion();

    /**
     * <pre>
     *副版本号
     * </pre>
     *
     * <code>int32 minorVersion = 3;</code>
     */
    int getMinorVersion();

    /**
     * <pre>
     *发布号
     * </pre>
     *
     * <code>int32 release = 4;</code>
     */
    int getRelease();

    /**
     * <code>string fileName = 5;</code>
     */
    java.lang.String getFileName();
    /**
     * <code>string fileName = 5;</code>
     */
    com.google.protobuf.ByteString
        getFileNameBytes();
  }
  /**
   * <pre>
   * 同步热更新包
   * </pre>
   *
   * Protobuf type {@code com.ziv.SyncHotPack}
   */
  public  static final class SyncHotPack extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ziv.SyncHotPack)
      SyncHotPackOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SyncHotPack.newBuilder() to construct.
    private SyncHotPack(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SyncHotPack() {
      fileName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SyncHotPack(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              platform_ = input.readInt32();
              break;
            }
            case 16: {

              majorVersion_ = input.readInt32();
              break;
            }
            case 24: {

              minorVersion_ = input.readInt32();
              break;
            }
            case 32: {

              release_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              fileName_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_com_ziv_SyncHotPack_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_com_ziv_SyncHotPack_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Packer.SyncHotPack.class, Packer.SyncHotPack.Builder.class);
    }

    public static final int PLATFORM_FIELD_NUMBER = 1;
    private int platform_;
    /**
     * <pre>
     *1:android 2:ios
     * </pre>
     *
     * <code>int32 platform = 1;</code>
     */
    public int getPlatform() {
      return platform_;
    }

    public static final int MAJORVERSION_FIELD_NUMBER = 2;
    private int majorVersion_;
    /**
     * <pre>
     *主版本号
     * </pre>
     *
     * <code>int32 majorVersion = 2;</code>
     */
    public int getMajorVersion() {
      return majorVersion_;
    }

    public static final int MINORVERSION_FIELD_NUMBER = 3;
    private int minorVersion_;
    /**
     * <pre>
     *副版本号
     * </pre>
     *
     * <code>int32 minorVersion = 3;</code>
     */
    public int getMinorVersion() {
      return minorVersion_;
    }

    public static final int RELEASE_FIELD_NUMBER = 4;
    private int release_;
    /**
     * <pre>
     *发布号
     * </pre>
     *
     * <code>int32 release = 4;</code>
     */
    public int getRelease() {
      return release_;
    }

    public static final int FILENAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object fileName_;
    /**
     * <code>string fileName = 5;</code>
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      }
    }
    /**
     * <code>string fileName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (platform_ != 0) {
        output.writeInt32(1, platform_);
      }
      if (majorVersion_ != 0) {
        output.writeInt32(2, majorVersion_);
      }
      if (minorVersion_ != 0) {
        output.writeInt32(3, minorVersion_);
      }
      if (release_ != 0) {
        output.writeInt32(4, release_);
      }
      if (!getFileNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, fileName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (platform_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, platform_);
      }
      if (majorVersion_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, majorVersion_);
      }
      if (minorVersion_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, minorVersion_);
      }
      if (release_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, release_);
      }
      if (!getFileNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, fileName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Packer.SyncHotPack)) {
        return super.equals(obj);
      }
      Packer.SyncHotPack other = (Packer.SyncHotPack) obj;

      if (getPlatform()
          != other.getPlatform()) return false;
      if (getMajorVersion()
          != other.getMajorVersion()) return false;
      if (getMinorVersion()
          != other.getMinorVersion()) return false;
      if (getRelease()
          != other.getRelease()) return false;
      if (!getFileName()
          .equals(other.getFileName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PLATFORM_FIELD_NUMBER;
      hash = (53 * hash) + getPlatform();
      hash = (37 * hash) + MAJORVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getMajorVersion();
      hash = (37 * hash) + MINORVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getMinorVersion();
      hash = (37 * hash) + RELEASE_FIELD_NUMBER;
      hash = (53 * hash) + getRelease();
      hash = (37 * hash) + FILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getFileName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Packer.SyncHotPack parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Packer.SyncHotPack parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Packer.SyncHotPack parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Packer.SyncHotPack parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Packer.SyncHotPack parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Packer.SyncHotPack parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Packer.SyncHotPack parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Packer.SyncHotPack parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Packer.SyncHotPack parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Packer.SyncHotPack parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Packer.SyncHotPack parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Packer.SyncHotPack parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Packer.SyncHotPack prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 同步热更新包
     * </pre>
     *
     * Protobuf type {@code com.ziv.SyncHotPack}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ziv.SyncHotPack)
        Packer.SyncHotPackOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_com_ziv_SyncHotPack_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_com_ziv_SyncHotPack_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Packer.SyncHotPack.class, Packer.SyncHotPack.Builder.class);
      }

      // Construct using org.game.packer.proto.Packer.SyncHotPack.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        platform_ = 0;

        majorVersion_ = 0;

        minorVersion_ = 0;

        release_ = 0;

        fileName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_com_ziv_SyncHotPack_descriptor;
      }

      @java.lang.Override
      public Packer.SyncHotPack getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @java.lang.Override
      public Packer.SyncHotPack build() {
        Packer.SyncHotPack result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Packer.SyncHotPack buildPartial() {
        Packer.SyncHotPack result = new Packer.SyncHotPack(this);
        result.platform_ = platform_;
        result.majorVersion_ = majorVersion_;
        result.minorVersion_ = minorVersion_;
        result.release_ = release_;
        result.fileName_ = fileName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Packer.SyncHotPack) {
          return mergeFrom((Packer.SyncHotPack)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Packer.SyncHotPack other) {
        if (other == getDefaultInstance()) return this;
        if (other.getPlatform() != 0) {
          setPlatform(other.getPlatform());
        }
        if (other.getMajorVersion() != 0) {
          setMajorVersion(other.getMajorVersion());
        }
        if (other.getMinorVersion() != 0) {
          setMinorVersion(other.getMinorVersion());
        }
        if (other.getRelease() != 0) {
          setRelease(other.getRelease());
        }
        if (!other.getFileName().isEmpty()) {
          fileName_ = other.fileName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Packer.SyncHotPack parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Packer.SyncHotPack) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int platform_ ;
      /**
       * <pre>
       *1:android 2:ios
       * </pre>
       *
       * <code>int32 platform = 1;</code>
       */
      public int getPlatform() {
        return platform_;
      }
      /**
       * <pre>
       *1:android 2:ios
       * </pre>
       *
       * <code>int32 platform = 1;</code>
       */
      public Builder setPlatform(int value) {
        
        platform_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *1:android 2:ios
       * </pre>
       *
       * <code>int32 platform = 1;</code>
       */
      public Builder clearPlatform() {
        
        platform_ = 0;
        onChanged();
        return this;
      }

      private int majorVersion_ ;
      /**
       * <pre>
       *主版本号
       * </pre>
       *
       * <code>int32 majorVersion = 2;</code>
       */
      public int getMajorVersion() {
        return majorVersion_;
      }
      /**
       * <pre>
       *主版本号
       * </pre>
       *
       * <code>int32 majorVersion = 2;</code>
       */
      public Builder setMajorVersion(int value) {
        
        majorVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *主版本号
       * </pre>
       *
       * <code>int32 majorVersion = 2;</code>
       */
      public Builder clearMajorVersion() {
        
        majorVersion_ = 0;
        onChanged();
        return this;
      }

      private int minorVersion_ ;
      /**
       * <pre>
       *副版本号
       * </pre>
       *
       * <code>int32 minorVersion = 3;</code>
       */
      public int getMinorVersion() {
        return minorVersion_;
      }
      /**
       * <pre>
       *副版本号
       * </pre>
       *
       * <code>int32 minorVersion = 3;</code>
       */
      public Builder setMinorVersion(int value) {
        
        minorVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *副版本号
       * </pre>
       *
       * <code>int32 minorVersion = 3;</code>
       */
      public Builder clearMinorVersion() {
        
        minorVersion_ = 0;
        onChanged();
        return this;
      }

      private int release_ ;
      /**
       * <pre>
       *发布号
       * </pre>
       *
       * <code>int32 release = 4;</code>
       */
      public int getRelease() {
        return release_;
      }
      /**
       * <pre>
       *发布号
       * </pre>
       *
       * <code>int32 release = 4;</code>
       */
      public Builder setRelease(int value) {
        
        release_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发布号
       * </pre>
       *
       * <code>int32 release = 4;</code>
       */
      public Builder clearRelease() {
        
        release_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object fileName_ = "";
      /**
       * <code>string fileName = 5;</code>
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fileName = 5;</code>
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fileName = 5;</code>
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fileName = 5;</code>
       */
      public Builder clearFileName() {
        
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>string fileName = 5;</code>
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ziv.SyncHotPack)
    }

    // @@protoc_insertion_point(class_scope:com.ziv.SyncHotPack)
    private static final Packer.SyncHotPack DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Packer.SyncHotPack();
    }

    public static Packer.SyncHotPack getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SyncHotPack>
        PARSER = new com.google.protobuf.AbstractParser<SyncHotPack>() {
      @java.lang.Override
      public SyncHotPack parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SyncHotPack(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SyncHotPack> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SyncHotPack> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Packer.SyncHotPack getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ziv_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ziv_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ziv_SyncHotPack_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ziv_SyncHotPack_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014packer.proto\022\007com.ziv\"`\n\007Message\022!\n\007ms" +
      "gType\030\001 \001(\0162\020.com.ziv.MsgType\022+\n\013syncHot" +
      "Pack\030\002 \001(\0132\024.com.ziv.SyncHotPackH\000B\005\n\003Ms" +
      "g\"n\n\013SyncHotPack\022\020\n\010platform\030\001 \001(\005\022\024\n\014ma" +
      "jorVersion\030\002 \001(\005\022\024\n\014minorVersion\030\003 \001(\005\022\017" +
      "\n\007release\030\004 \001(\005\022\020\n\010fileName\030\005 \001(\t*\032\n\007Msg" +
      "Type\022\017\n\013SYNCHOTPACK\020\000B\032\n\020com.ziv.fs.prot" +
      "oB\006Packerb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ziv_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ziv_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ziv_Message_descriptor,
        new java.lang.String[] { "MsgType", "SyncHotPack", "Msg", });
    internal_static_com_ziv_SyncHotPack_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ziv_SyncHotPack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ziv_SyncHotPack_descriptor,
        new java.lang.String[] { "Platform", "MajorVersion", "MinorVersion", "Release", "FileName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
