// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgMahjong.proto

package com.sean.games.mahjong;

public final class MsgMahjong {
  private MsgMahjong() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.sean.games.mahjong.Direction}
   */
  public enum Direction
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>EAST = 0;</code>
     */
    EAST(0),
    /**
     * <code>SOUTH = 1;</code>
     */
    SOUTH(1),
    /**
     * <code>WEST = 2;</code>
     */
    WEST(2),
    /**
     * <code>NORTH = 3;</code>
     */
    NORTH(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>EAST = 0;</code>
     */
    public static final int EAST_VALUE = 0;
    /**
     * <code>SOUTH = 1;</code>
     */
    public static final int SOUTH_VALUE = 1;
    /**
     * <code>WEST = 2;</code>
     */
    public static final int WEST_VALUE = 2;
    /**
     * <code>NORTH = 3;</code>
     */
    public static final int NORTH_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Direction valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Direction forNumber(int value) {
      switch (value) {
        case 0: return EAST;
        case 1: return SOUTH;
        case 2: return WEST;
        case 3: return NORTH;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Direction>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Direction> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Direction>() {
            public Direction findValueByNumber(int number) {
              return Direction.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.sean.games.mahjong.MsgMahjong.getDescriptor().getEnumTypes().get(0);
    }

    private static final Direction[] VALUES = values();

    public static Direction valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Direction(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.sean.games.mahjong.Direction)
  }

  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.sean.games.mahjong.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.sean.games.mahjong.Deal deal = 1;</code>
     * @return Whether the deal field is set.
     */
    boolean hasDeal();
    /**
     * <code>.com.sean.games.mahjong.Deal deal = 1;</code>
     * @return The deal.
     */
    com.sean.games.mahjong.MsgMahjong.Deal getDeal();
    /**
     * <code>.com.sean.games.mahjong.Deal deal = 1;</code>
     */
    com.sean.games.mahjong.MsgMahjong.DealOrBuilder getDealOrBuilder();

    public com.sean.games.mahjong.MsgMahjong.Message.DataCase getDataCase();
  }
  /**
   * Protobuf type {@code com.sean.games.mahjong.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.sean.games.mahjong.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.sean.games.mahjong.MsgMahjong.Deal.Builder subBuilder = null;
              if (dataCase_ == 1) {
                subBuilder = ((com.sean.games.mahjong.MsgMahjong.Deal) data_).toBuilder();
              }
              data_ =
                  input.readMessage(com.sean.games.mahjong.MsgMahjong.Deal.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.sean.games.mahjong.MsgMahjong.Deal) data_);
                data_ = subBuilder.buildPartial();
              }
              dataCase_ = 1;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sean.games.mahjong.MsgMahjong.internal_static_com_sean_games_mahjong_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sean.games.mahjong.MsgMahjong.internal_static_com_sean_games_mahjong_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sean.games.mahjong.MsgMahjong.Message.class, com.sean.games.mahjong.MsgMahjong.Message.Builder.class);
    }

    private int dataCase_ = 0;
    private java.lang.Object data_;
    public enum DataCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      DEAL(1),
      DATA_NOT_SET(0);
      private final int value;
      private DataCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataCase forNumber(int value) {
        switch (value) {
          case 1: return DEAL;
          case 0: return DATA_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataCase
    getDataCase() {
      return DataCase.forNumber(
          dataCase_);
    }

    public static final int DEAL_FIELD_NUMBER = 1;
    /**
     * <code>.com.sean.games.mahjong.Deal deal = 1;</code>
     * @return Whether the deal field is set.
     */
    public boolean hasDeal() {
      return dataCase_ == 1;
    }
    /**
     * <code>.com.sean.games.mahjong.Deal deal = 1;</code>
     * @return The deal.
     */
    public com.sean.games.mahjong.MsgMahjong.Deal getDeal() {
      if (dataCase_ == 1) {
         return (com.sean.games.mahjong.MsgMahjong.Deal) data_;
      }
      return com.sean.games.mahjong.MsgMahjong.Deal.getDefaultInstance();
    }
    /**
     * <code>.com.sean.games.mahjong.Deal deal = 1;</code>
     */
    public com.sean.games.mahjong.MsgMahjong.DealOrBuilder getDealOrBuilder() {
      if (dataCase_ == 1) {
         return (com.sean.games.mahjong.MsgMahjong.Deal) data_;
      }
      return com.sean.games.mahjong.MsgMahjong.Deal.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dataCase_ == 1) {
        output.writeMessage(1, (com.sean.games.mahjong.MsgMahjong.Deal) data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dataCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (com.sean.games.mahjong.MsgMahjong.Deal) data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sean.games.mahjong.MsgMahjong.Message)) {
        return super.equals(obj);
      }
      com.sean.games.mahjong.MsgMahjong.Message other = (com.sean.games.mahjong.MsgMahjong.Message) obj;

      if (!getDataCase().equals(other.getDataCase())) return false;
      switch (dataCase_) {
        case 1:
          if (!getDeal()
              .equals(other.getDeal())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (dataCase_) {
        case 1:
          hash = (37 * hash) + DEAL_FIELD_NUMBER;
          hash = (53 * hash) + getDeal().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sean.games.mahjong.MsgMahjong.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sean.games.mahjong.MsgMahjong.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sean.games.mahjong.MsgMahjong.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sean.games.mahjong.MsgMahjong.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sean.games.mahjong.MsgMahjong.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sean.games.mahjong.MsgMahjong.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sean.games.mahjong.MsgMahjong.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sean.games.mahjong.MsgMahjong.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sean.games.mahjong.MsgMahjong.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sean.games.mahjong.MsgMahjong.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sean.games.mahjong.MsgMahjong.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sean.games.mahjong.MsgMahjong.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sean.games.mahjong.MsgMahjong.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.sean.games.mahjong.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.sean.games.mahjong.Message)
        com.sean.games.mahjong.MsgMahjong.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sean.games.mahjong.MsgMahjong.internal_static_com_sean_games_mahjong_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sean.games.mahjong.MsgMahjong.internal_static_com_sean_games_mahjong_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sean.games.mahjong.MsgMahjong.Message.class, com.sean.games.mahjong.MsgMahjong.Message.Builder.class);
      }

      // Construct using com.sean.games.mahjong.MsgMahjong.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dataCase_ = 0;
        data_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sean.games.mahjong.MsgMahjong.internal_static_com_sean_games_mahjong_Message_descriptor;
      }

      @java.lang.Override
      public com.sean.games.mahjong.MsgMahjong.Message getDefaultInstanceForType() {
        return com.sean.games.mahjong.MsgMahjong.Message.getDefaultInstance();
      }

      @java.lang.Override
      public com.sean.games.mahjong.MsgMahjong.Message build() {
        com.sean.games.mahjong.MsgMahjong.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sean.games.mahjong.MsgMahjong.Message buildPartial() {
        com.sean.games.mahjong.MsgMahjong.Message result = new com.sean.games.mahjong.MsgMahjong.Message(this);
        if (dataCase_ == 1) {
          if (dealBuilder_ == null) {
            result.data_ = data_;
          } else {
            result.data_ = dealBuilder_.build();
          }
        }
        result.dataCase_ = dataCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sean.games.mahjong.MsgMahjong.Message) {
          return mergeFrom((com.sean.games.mahjong.MsgMahjong.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sean.games.mahjong.MsgMahjong.Message other) {
        if (other == com.sean.games.mahjong.MsgMahjong.Message.getDefaultInstance()) return this;
        switch (other.getDataCase()) {
          case DEAL: {
            mergeDeal(other.getDeal());
            break;
          }
          case DATA_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sean.games.mahjong.MsgMahjong.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sean.games.mahjong.MsgMahjong.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataCase_ = 0;
      private java.lang.Object data_;
      public DataCase
          getDataCase() {
        return DataCase.forNumber(
            dataCase_);
      }

      public Builder clearData() {
        dataCase_ = 0;
        data_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          com.sean.games.mahjong.MsgMahjong.Deal, com.sean.games.mahjong.MsgMahjong.Deal.Builder, com.sean.games.mahjong.MsgMahjong.DealOrBuilder> dealBuilder_;
      /**
       * <code>.com.sean.games.mahjong.Deal deal = 1;</code>
       * @return Whether the deal field is set.
       */
      public boolean hasDeal() {
        return dataCase_ == 1;
      }
      /**
       * <code>.com.sean.games.mahjong.Deal deal = 1;</code>
       * @return The deal.
       */
      public com.sean.games.mahjong.MsgMahjong.Deal getDeal() {
        if (dealBuilder_ == null) {
          if (dataCase_ == 1) {
            return (com.sean.games.mahjong.MsgMahjong.Deal) data_;
          }
          return com.sean.games.mahjong.MsgMahjong.Deal.getDefaultInstance();
        } else {
          if (dataCase_ == 1) {
            return dealBuilder_.getMessage();
          }
          return com.sean.games.mahjong.MsgMahjong.Deal.getDefaultInstance();
        }
      }
      /**
       * <code>.com.sean.games.mahjong.Deal deal = 1;</code>
       */
      public Builder setDeal(com.sean.games.mahjong.MsgMahjong.Deal value) {
        if (dealBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          dealBuilder_.setMessage(value);
        }
        dataCase_ = 1;
        return this;
      }
      /**
       * <code>.com.sean.games.mahjong.Deal deal = 1;</code>
       */
      public Builder setDeal(
          com.sean.games.mahjong.MsgMahjong.Deal.Builder builderForValue) {
        if (dealBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          dealBuilder_.setMessage(builderForValue.build());
        }
        dataCase_ = 1;
        return this;
      }
      /**
       * <code>.com.sean.games.mahjong.Deal deal = 1;</code>
       */
      public Builder mergeDeal(com.sean.games.mahjong.MsgMahjong.Deal value) {
        if (dealBuilder_ == null) {
          if (dataCase_ == 1 &&
              data_ != com.sean.games.mahjong.MsgMahjong.Deal.getDefaultInstance()) {
            data_ = com.sean.games.mahjong.MsgMahjong.Deal.newBuilder((com.sean.games.mahjong.MsgMahjong.Deal) data_)
                .mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          if (dataCase_ == 1) {
            dealBuilder_.mergeFrom(value);
          }
          dealBuilder_.setMessage(value);
        }
        dataCase_ = 1;
        return this;
      }
      /**
       * <code>.com.sean.games.mahjong.Deal deal = 1;</code>
       */
      public Builder clearDeal() {
        if (dealBuilder_ == null) {
          if (dataCase_ == 1) {
            dataCase_ = 0;
            data_ = null;
            onChanged();
          }
        } else {
          if (dataCase_ == 1) {
            dataCase_ = 0;
            data_ = null;
          }
          dealBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.com.sean.games.mahjong.Deal deal = 1;</code>
       */
      public com.sean.games.mahjong.MsgMahjong.Deal.Builder getDealBuilder() {
        return getDealFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.sean.games.mahjong.Deal deal = 1;</code>
       */
      public com.sean.games.mahjong.MsgMahjong.DealOrBuilder getDealOrBuilder() {
        if ((dataCase_ == 1) && (dealBuilder_ != null)) {
          return dealBuilder_.getMessageOrBuilder();
        } else {
          if (dataCase_ == 1) {
            return (com.sean.games.mahjong.MsgMahjong.Deal) data_;
          }
          return com.sean.games.mahjong.MsgMahjong.Deal.getDefaultInstance();
        }
      }
      /**
       * <code>.com.sean.games.mahjong.Deal deal = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.sean.games.mahjong.MsgMahjong.Deal, com.sean.games.mahjong.MsgMahjong.Deal.Builder, com.sean.games.mahjong.MsgMahjong.DealOrBuilder> 
          getDealFieldBuilder() {
        if (dealBuilder_ == null) {
          if (!(dataCase_ == 1)) {
            data_ = com.sean.games.mahjong.MsgMahjong.Deal.getDefaultInstance();
          }
          dealBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.sean.games.mahjong.MsgMahjong.Deal, com.sean.games.mahjong.MsgMahjong.Deal.Builder, com.sean.games.mahjong.MsgMahjong.DealOrBuilder>(
                  (com.sean.games.mahjong.MsgMahjong.Deal) data_,
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        dataCase_ = 1;
        onChanged();;
        return dealBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.sean.games.mahjong.Message)
    }

    // @@protoc_insertion_point(class_scope:com.sean.games.mahjong.Message)
    private static final com.sean.games.mahjong.MsgMahjong.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sean.games.mahjong.MsgMahjong.Message();
    }

    public static com.sean.games.mahjong.MsgMahjong.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sean.games.mahjong.MsgMahjong.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DealOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.sean.games.mahjong.Deal)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.sean.games.mahjong.Direction seat = 1;</code>
     * @return The enum numeric value on the wire for seat.
     */
    int getSeatValue();
    /**
     * <code>.com.sean.games.mahjong.Direction seat = 1;</code>
     * @return The seat.
     */
    com.sean.games.mahjong.MsgMahjong.Direction getSeat();

    /**
     * <code>repeated int32 cards = 2;</code>
     * @return A list containing the cards.
     */
    java.util.List<java.lang.Integer> getCardsList();
    /**
     * <code>repeated int32 cards = 2;</code>
     * @return The count of cards.
     */
    int getCardsCount();
    /**
     * <code>repeated int32 cards = 2;</code>
     * @param index The index of the element to return.
     * @return The cards at the given index.
     */
    int getCards(int index);
  }
  /**
   * <pre>
   * 发牌
   * </pre>
   *
   * Protobuf type {@code com.sean.games.mahjong.Deal}
   */
  public  static final class Deal extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.sean.games.mahjong.Deal)
      DealOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Deal.newBuilder() to construct.
    private Deal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Deal() {
      seat_ = 0;
      cards_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Deal();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Deal(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              seat_ = rawValue;
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                cards_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              cards_.addInt(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                cards_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                cards_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          cards_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sean.games.mahjong.MsgMahjong.internal_static_com_sean_games_mahjong_Deal_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sean.games.mahjong.MsgMahjong.internal_static_com_sean_games_mahjong_Deal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sean.games.mahjong.MsgMahjong.Deal.class, com.sean.games.mahjong.MsgMahjong.Deal.Builder.class);
    }

    public static final int SEAT_FIELD_NUMBER = 1;
    private int seat_;
    /**
     * <code>.com.sean.games.mahjong.Direction seat = 1;</code>
     * @return The enum numeric value on the wire for seat.
     */
    public int getSeatValue() {
      return seat_;
    }
    /**
     * <code>.com.sean.games.mahjong.Direction seat = 1;</code>
     * @return The seat.
     */
    public com.sean.games.mahjong.MsgMahjong.Direction getSeat() {
      @SuppressWarnings("deprecation")
      com.sean.games.mahjong.MsgMahjong.Direction result = com.sean.games.mahjong.MsgMahjong.Direction.valueOf(seat_);
      return result == null ? com.sean.games.mahjong.MsgMahjong.Direction.UNRECOGNIZED : result;
    }

    public static final int CARDS_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.IntList cards_;
    /**
     * <code>repeated int32 cards = 2;</code>
     * @return A list containing the cards.
     */
    public java.util.List<java.lang.Integer>
        getCardsList() {
      return cards_;
    }
    /**
     * <code>repeated int32 cards = 2;</code>
     * @return The count of cards.
     */
    public int getCardsCount() {
      return cards_.size();
    }
    /**
     * <code>repeated int32 cards = 2;</code>
     * @param index The index of the element to return.
     * @return The cards at the given index.
     */
    public int getCards(int index) {
      return cards_.getInt(index);
    }
    private int cardsMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (seat_ != com.sean.games.mahjong.MsgMahjong.Direction.EAST.getNumber()) {
        output.writeEnum(1, seat_);
      }
      if (getCardsList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(cardsMemoizedSerializedSize);
      }
      for (int i = 0; i < cards_.size(); i++) {
        output.writeInt32NoTag(cards_.getInt(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (seat_ != com.sean.games.mahjong.MsgMahjong.Direction.EAST.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, seat_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < cards_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(cards_.getInt(i));
        }
        size += dataSize;
        if (!getCardsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        cardsMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sean.games.mahjong.MsgMahjong.Deal)) {
        return super.equals(obj);
      }
      com.sean.games.mahjong.MsgMahjong.Deal other = (com.sean.games.mahjong.MsgMahjong.Deal) obj;

      if (seat_ != other.seat_) return false;
      if (!getCardsList()
          .equals(other.getCardsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SEAT_FIELD_NUMBER;
      hash = (53 * hash) + seat_;
      if (getCardsCount() > 0) {
        hash = (37 * hash) + CARDS_FIELD_NUMBER;
        hash = (53 * hash) + getCardsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sean.games.mahjong.MsgMahjong.Deal parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sean.games.mahjong.MsgMahjong.Deal parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sean.games.mahjong.MsgMahjong.Deal parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sean.games.mahjong.MsgMahjong.Deal parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sean.games.mahjong.MsgMahjong.Deal parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sean.games.mahjong.MsgMahjong.Deal parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sean.games.mahjong.MsgMahjong.Deal parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sean.games.mahjong.MsgMahjong.Deal parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sean.games.mahjong.MsgMahjong.Deal parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sean.games.mahjong.MsgMahjong.Deal parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sean.games.mahjong.MsgMahjong.Deal parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sean.games.mahjong.MsgMahjong.Deal parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sean.games.mahjong.MsgMahjong.Deal prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 发牌
     * </pre>
     *
     * Protobuf type {@code com.sean.games.mahjong.Deal}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.sean.games.mahjong.Deal)
        com.sean.games.mahjong.MsgMahjong.DealOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sean.games.mahjong.MsgMahjong.internal_static_com_sean_games_mahjong_Deal_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sean.games.mahjong.MsgMahjong.internal_static_com_sean_games_mahjong_Deal_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sean.games.mahjong.MsgMahjong.Deal.class, com.sean.games.mahjong.MsgMahjong.Deal.Builder.class);
      }

      // Construct using com.sean.games.mahjong.MsgMahjong.Deal.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        seat_ = 0;

        cards_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sean.games.mahjong.MsgMahjong.internal_static_com_sean_games_mahjong_Deal_descriptor;
      }

      @java.lang.Override
      public com.sean.games.mahjong.MsgMahjong.Deal getDefaultInstanceForType() {
        return com.sean.games.mahjong.MsgMahjong.Deal.getDefaultInstance();
      }

      @java.lang.Override
      public com.sean.games.mahjong.MsgMahjong.Deal build() {
        com.sean.games.mahjong.MsgMahjong.Deal result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sean.games.mahjong.MsgMahjong.Deal buildPartial() {
        com.sean.games.mahjong.MsgMahjong.Deal result = new com.sean.games.mahjong.MsgMahjong.Deal(this);
        int from_bitField0_ = bitField0_;
        result.seat_ = seat_;
        if (((bitField0_ & 0x00000001) != 0)) {
          cards_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.cards_ = cards_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sean.games.mahjong.MsgMahjong.Deal) {
          return mergeFrom((com.sean.games.mahjong.MsgMahjong.Deal)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sean.games.mahjong.MsgMahjong.Deal other) {
        if (other == com.sean.games.mahjong.MsgMahjong.Deal.getDefaultInstance()) return this;
        if (other.seat_ != 0) {
          setSeatValue(other.getSeatValue());
        }
        if (!other.cards_.isEmpty()) {
          if (cards_.isEmpty()) {
            cards_ = other.cards_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCardsIsMutable();
            cards_.addAll(other.cards_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sean.games.mahjong.MsgMahjong.Deal parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sean.games.mahjong.MsgMahjong.Deal) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int seat_ = 0;
      /**
       * <code>.com.sean.games.mahjong.Direction seat = 1;</code>
       * @return The enum numeric value on the wire for seat.
       */
      public int getSeatValue() {
        return seat_;
      }
      /**
       * <code>.com.sean.games.mahjong.Direction seat = 1;</code>
       * @param value The enum numeric value on the wire for seat to set.
       * @return This builder for chaining.
       */
      public Builder setSeatValue(int value) {
        seat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.sean.games.mahjong.Direction seat = 1;</code>
       * @return The seat.
       */
      public com.sean.games.mahjong.MsgMahjong.Direction getSeat() {
        @SuppressWarnings("deprecation")
        com.sean.games.mahjong.MsgMahjong.Direction result = com.sean.games.mahjong.MsgMahjong.Direction.valueOf(seat_);
        return result == null ? com.sean.games.mahjong.MsgMahjong.Direction.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.sean.games.mahjong.Direction seat = 1;</code>
       * @param value The seat to set.
       * @return This builder for chaining.
       */
      public Builder setSeat(com.sean.games.mahjong.MsgMahjong.Direction value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        seat_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.sean.games.mahjong.Direction seat = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSeat() {
        
        seat_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList cards_ = emptyIntList();
      private void ensureCardsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          cards_ = mutableCopy(cards_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 cards = 2;</code>
       * @return A list containing the cards.
       */
      public java.util.List<java.lang.Integer>
          getCardsList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(cards_) : cards_;
      }
      /**
       * <code>repeated int32 cards = 2;</code>
       * @return The count of cards.
       */
      public int getCardsCount() {
        return cards_.size();
      }
      /**
       * <code>repeated int32 cards = 2;</code>
       * @param index The index of the element to return.
       * @return The cards at the given index.
       */
      public int getCards(int index) {
        return cards_.getInt(index);
      }
      /**
       * <code>repeated int32 cards = 2;</code>
       * @param index The index to set the value at.
       * @param value The cards to set.
       * @return This builder for chaining.
       */
      public Builder setCards(
          int index, int value) {
        ensureCardsIsMutable();
        cards_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 cards = 2;</code>
       * @param value The cards to add.
       * @return This builder for chaining.
       */
      public Builder addCards(int value) {
        ensureCardsIsMutable();
        cards_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 cards = 2;</code>
       * @param values The cards to add.
       * @return This builder for chaining.
       */
      public Builder addAllCards(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureCardsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, cards_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 cards = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCards() {
        cards_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.sean.games.mahjong.Deal)
    }

    // @@protoc_insertion_point(class_scope:com.sean.games.mahjong.Deal)
    private static final com.sean.games.mahjong.MsgMahjong.Deal DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sean.games.mahjong.MsgMahjong.Deal();
    }

    public static com.sean.games.mahjong.MsgMahjong.Deal getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Deal>
        PARSER = new com.google.protobuf.AbstractParser<Deal>() {
      @java.lang.Override
      public Deal parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Deal(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Deal> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Deal> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sean.games.mahjong.MsgMahjong.Deal getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sean_games_mahjong_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sean_games_mahjong_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sean_games_mahjong_Deal_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sean_games_mahjong_Deal_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020MsgMahjong.proto\022\026com.sean.games.mahjo" +
      "ng\"?\n\007Message\022,\n\004deal\030\001 \001(\0132\034.com.sean.g" +
      "ames.mahjong.DealH\000B\006\n\004data\"F\n\004Deal\022/\n\004s" +
      "eat\030\001 \001(\0162!.com.sean.games.mahjong.Direc" +
      "tion\022\r\n\005cards\030\002 \003(\005*5\n\tDirection\022\010\n\004EAST" +
      "\020\000\022\t\n\005SOUTH\020\001\022\010\n\004WEST\020\002\022\t\n\005NORTH\020\003b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_sean_games_mahjong_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_sean_games_mahjong_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sean_games_mahjong_Message_descriptor,
        new java.lang.String[] { "Deal", "Data", });
    internal_static_com_sean_games_mahjong_Deal_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_sean_games_mahjong_Deal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sean_games_mahjong_Deal_descriptor,
        new java.lang.String[] { "Seat", "Cards", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
